src/Gesseh/CoreBundle/Entity/Department.php
<?php

namespace Gesseh\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gesseh\CoreBundle\Entity\Hospital;

/**
 * Department
 *
 * @ORM\Table(name="department")
 * @ORM\Entity(repositoryClass="Gesseh\CoreBundle\Entity\DepartmentRepository")
 */
class Department
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100, nullable=false)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="head", type="string", length=100, nullable=true)
     */
    private $head;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100, nullable=true)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="phone", type="string", length=25, nullable=true)
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="Gesseh\CoreBundle\Entity\Hospital", inversedBy="departments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $hospital;

    /** @ORM\OneToMany(targetEntity="Gesseh\CoreBundle\Entity\Job", mappedBy="department", cascade={"persist","remove"})
     */
    private $jobs;


    public function __construct()
    {
        $this->jobs = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Department
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set head
     *
     * @param string $head
     * @return Department
     */
    public function setHead($head)
    {
        $this->head = $head;

        return $this;
    }

    /**
     * Get head
     *
     * @return string 
     */
    public function getHead()
    {
        return $this->head;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Department
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return Department
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Department
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set hospital
     *
     * @param Hospital $hospital
     * @return Department
     */
    public function setHospital(Hospital $hospital)
    {
        $this->hospital = $hospital;

        return $this;
    }

    /**
     * Get hospital
     *
     * @return Hospital 
     */
    public function getHospital()
    {
        return $this->hospital;
    }


    public function __toString()
    {
        return $this->name;
    }

    public function getCompleteTitle()
    {
        return $this->getHospital()->getName().' - '.$this->getName();
    }
}

src/Gesseh/CoreBundle/Controller/JobAllocationAdminController.php
<?php

namespace Gesseh\CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;

use Gesseh\CoreBundle\Entity\JobAllocation;
use Gesseh\CoreBundle\Entity\JobAllocationPriority;
use Gesseh\CoreBundle\Entity\JobAllocationPeriod;
use Gesseh\CoreBundle\Form\JobAllocationJobAutoType;
use Gesseh\CoreBundle\Form\JobAllocationUserAutoType;
use Gesseh\CoreBundle\Form\JobAllocationPriorityType;
use Gesseh\CoreBundle\Form\JobAllocationPriorityUserAutoType;
use Gesseh\CoreBundle\Form\JobAllocationPeriodType;


/**
 * @Route("/admin/joballocation")
 * @Security("has_role('ROLE_ADMIN_JOB_ALLOCATION')")
 */
class JobAllocationAdminController extends Controller
{

    /**
     * Manage users allocated for a job
     *
     * @Route("/{id}/usersmanagement", name="GCore_AdminJobAllocationManagement", requirements={"id" = "\d+"})
     * @Template()
     */
    public function manageJobAllocationsAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $job = $em->getRepository('GessehCoreBundle:Job')->find($id);

        if (null == $job) {
            throw $this->createNotFoundException("Unable to find this job");
        }

        $jobAllocations = $em->getRepository('GessehCoreBundle:JobAllocation')->getByJob($id);

        return array(
            'job' => $job,
            'jobAllocations' => $jobAllocations
        );
    }

    /**
     * Manage period of job allocations
     *
     * @Route("/periods/{id}",
     name="GCore_AdminJobAllocationPeriods",
     requirements={"id" = "\d+"},
     defaults={"id" = -1})
     * @Template()
     */
    public function manageJobAllocationPeriodsAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $jobAllocationPeriods = $em->getRepository('GessehCoreBundle:JobAllocationPeriod')->getCompleteByGroups($this->get('gesseh_user.role_checker')->getReachableObjects('ROLE_ADMIN_JOB_ALLOCATION', 'Group'));

        $newJobAllocationPeriod = null;
        
        if ($id >= 0) {
            foreach ($jobAllocationPeriods as $jobAllocationPeriod) {
                if ($id == $jobAllocationPeriod->getId()) {
                    $newJobAllocationPeriod = $jobAllocationPeriod;
                }
            }
        }

        if (null == $newJobAllocationPeriod) {
            $newJobAllocationPeriod = new JobAllocationPeriod();
        }

        $newJobAllocationPeriod->setCompleted(false);

        $form = $this->createForm('job_allocation_period', $newJobAllocationPeriod);

        $request = $this->getRequest();

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em->persist($newJobAllocationPeriod);
            $em->flush();

            return $this->redirect($this->generateUrl('GCore_AdminJobAllocationPeriods'));
        }

        return array (
            'id' => $id,
            'jobAllocationPeriods' => $jobAllocationPeriods,
            'form' => $form->createView()
        );
    }

    
    /**
     * Manage job allocation period completion
     *
     * @Route("/period/{id}/completion",
     name="GCore_AdminJobAllocationPeriodCompletion",
     requirements={"id" = "\d+"})
    */
    public function changeJobAllocationPeriodCompletionAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $jobAllocationPeriod = $em->getRepository('GessehCoreBundle:JobAllocationPeriod')->find($id);

        $jobAllocationPeriod->setCompleted(! $jobAllocationPeriod->isCompleted());

        $em->flush();

        return $this->redirect($this->generateUrl('GCore_AdminJobAllocationPeriods'));
    }
    
    
    /**
     * Manage job allocations for a period
     *
     * @Route("/period/{periodId}/{userId}/{jobAllocationId}",
     name="GCore_AdminJobAllocationForPeriod",
     requirements={"periodId" = "\d+", "userId" = "\d+", "jobAllocationId" = "\d+"},
     defaults={"userId" = -1, "jobAllocationId" = -1})
     * @Template()
     */
    public function manageJobAllocationsForPeriodAction(Request $request, $periodId, $userId, $jobAllocationId)
    {
        if ($userId < 0 and null != $request->request->get('userId')) {
            $userId = $request->request->get('userId');
        }
        
        $em = $this->getDoctrine()->getManager();

        $jobAllocationPeriod = $em->getRepository('GessehCoreBundle:JobAllocationPeriod')->getComplete($periodId);

        if (null == $jobAllocationPeriod) {
            throw $this->createNotFoundException("Unable to find this job allocation period"); 
        }

        
        /* $jobAllocations = $jobAllocationPeriod->getJobAllocations()->toArray(); */

        $groups = $this->get('gesseh_user.groups_hierarchy')->getReachableGroups($jobAllocationPeriod->getGroups()->toArray());
        
        $jobs = $em->getRepository('GessehCoreBundle:Job')->getJobWithAffiliationsByGroups($this->get('gesseh_user.groups_hierarchy')->getParentGroups($groups));

        $jobAllocations = $em->getRepository('GessehCoreBundle:JobAllocation')->getByJobsAndPeriod($jobs, $jobAllocationPeriod);
        foreach ($jobAllocationPeriod->getJobAllocations() as $jobAllocation) {
            if (! in_array($jobAllocation, $jobAllocations)) {
                $jobAllocations[] = $jobAllocation;
            }
        }

        // for validation
        $this->get('gesseh_core.job_allocation_period_handler')->setJobAllocations($jobAllocations);

        
        $alreadyAllocatedUsers = array();
        foreach ($jobAllocationPeriod->getJobAllocations() as $jobAllocation) {
            $alreadyAllocatedUsers[] = $jobAllocation->getUser();
        }
        
        $users = $em->getRepository('GessehUserBundle:User')->getCompleteByGroup($groups, $jobAllocationPeriod);

        $users = $this->get('gesseh_user.priority_handler')->getUsersByPriorityPeriod($users, $groups, $jobAllocationPeriod, 'jobAllocation');
        if (count ($users) < 1) {
            $this->get('session')->getFlashBag()->add('notice', "No users found for this job allocation period");
            return $this->redirect($this->generateUrl('GCore_AdminJobAllocationPeriods'));
        }
        ///////
        /* foreach ($users as $u) { */
        /*     echo $u->__toString().'<br>'; */
        /* } */
        /////

        $userToAllocate = null;
        foreach ($users as $key => $user) {
            $managedUser = $key;
            
            if ($userId >= 0) {
                if ($userId == $user->getId()) {
                    $userToAllocate = $user;
                    break;
                }
            }
            elseif (! in_array($user, $alreadyAllocatedUsers)) {
                $userToAllocate = $user;
                break;
            }
        }

        $allUsersAllocated = false;
        
        if (null == $userToAllocate) {
            if ($userId >= 0) {
                throw $this->createNotFoundException("User not found"); 
            }
            else {
                $allUsersAllocated = true;
                $this->get('session')->getFlashBag()->add('notice', "All users already have a job");
                /* return $this->redirect($this->generateUrl('GCore_AdminJobAllocationForPeriod', array('periodId' => $periodId, 'userId' => $jobAllocationPriorities[0]->getUser()->getId()))); */
                $userToAllocate = $users[0];
            }
        }
        
        $hospitals = array();
        $departments = array();
        foreach ($jobs as $job) {
            $department = $job->getDepartment();
            if (! in_array ($department, $departments)) {
                $departments[] = $department;
                if (! in_array ($department->getHospital(), $hospitals)) {
                        $hospitals[] = $department->getHospital();
                    }
            }
        }

        $newJobAllocation = null;
        
        foreach ($jobAllocationPeriod->getJobAllocations() as $jobAllocation) {
            if ($jobAllocationId == $jobAllocation->getId() or ($jobAllocationId < 0 and $userToAllocate == $jobAllocation->getUser())) {
                $newJobAllocation = $jobAllocation;
            }
        }

        if (null == $newJobAllocation) {
            $newJobAllocation = new JobAllocation();
            $newJobAllocation->setStartDate($jobAllocationPeriod->getStartDate());
            $newJobAllocation->setEndDate($jobAllocationPeriod->getEndDate());
            $newJobAllocation->setUser($userToAllocate);
            $newJobAllocation->setJobAllocationPeriod($jobAllocationPeriod);
        }

        $form = $this->createForm(new JobAllocationUserAutoType($jobs), $newJobAllocation);

        $request = $this->getRequest();

        $form->handleRequest($request);

        $nextUser = null;
        if (isset ($users[$managedUser +1])) {
            $nextUser = $users[$managedUser +1];
        }
            
        if ($form->get('cancel')->isClicked()) {
            return $this->redirect($this->generateUrl('GCore_AdminJobAllocationForPeriod', array('periodId' => $periodId, 'userId' => null != $nextUser?$nextUser->getId():-1)));
        }
        elseif ($form->get('remove')->isClicked()) {
            $em->remove($newJobAllocation);
            $em->flush();

            return $this->redirect($this->generateUrl('GCore_AdminJobAllocationForPeriod', array('periodId' => $periodId, 'userId' => $newJobAllocation->getUser()->getId(), 'jobAllocationId' => 0)));
        }
        elseif ($form->isValid()) {
            $em->persist($newJobAllocation);
            $em->flush();

            if ($form->get('saveAndAdd')->isClicked()) {

src/Gesseh/CoreBundle/Resources/views/JobAllocationAdmin/allocateUserToJob.html.twig
{% extends "GessehCoreBundle::layout.html.twig" %}

{% block core_content %}

    {{ form_start(user_job_allocation_form, {'attr': {'novalidate': 'novalidate'}}) }}

    {{ form_widget(user_job_allocation_form) }}

    {{ form_end(user_job_allocation_form) }}

    <p>
        <a href='{{ path('GCore_AdminJobAllocationManagement', {'id': job.id}) }}'>Cancel</a>
    </p>

{% endblock core_content %}

src/Gesseh/CoreBundle/Resources/views/JobAllocationAdmin/manageJobAllocationPeriods.html.twig
{% extends "GessehCoreBundle::layout.html.twig" %}

{% block core_content %}
    {% form_theme form 'GessehCoreBundle:Form:fields.html.twig' %}
    
    <table>
        <thead>
            <tr>
                <td>Start date</td>
                <td>End date</td>
                <td>Groups</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            {% for jobAllocationPeriod in jobAllocationPeriods %}
                <tr>
	            {% if id == jobAllocationPeriod.id %}
	                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                        <td>
	                    {{ form_widget(form.startDate) }}
                        </td>
                        <td>
                            {{ form_widget(form.endDate) }}
                        </td>
                        <td>
                            {{ form_widget(form.groups) }}
                        </td>
                        <td>
                            {{ form_widget(form.save) }}
                            {{ form_widget(form.reset) }}
                            <a href="{{ path('GCore_AdminJobAllocationPeriods') }}" class="btn btn-default">
                                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                                Cancel
                            </a>
                        </td>
	                {{ form_end(form) }}
	            {% else %}
                        <td>
	                    {{ jobAllocationPeriod.startDate|date("d/m/Y") }}
                        </td>
                        <td>
	                    {{ jobAllocationPeriod.endDate|date("d/m/Y") }}
                        </td>
                        <td>
                            <ul>
                                {% for group in jobAllocationPeriod.groups %}
                                    <li>{{ group.completeTitle }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <!-- <ul>
                            <li> -->
	                    {% if jobAllocationPeriod.completed == true %}
		                completed
                                <a href="{{ path('GCore_AdminJobAllocationPeriodCompletion', {'id':jobAllocationPeriod.id}) }}" title="unlock">
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                </a>
	                    {% else %}
		                <a href="{{ path('GCore_AdminJobAllocationPeriods', {'id':jobAllocationPeriod.id}) }}" title="change period">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </a>
	                    {% endif %}
                            <!-- </li>
                            <li> -->
	                    <a href="{{ path('GCore_AdminJobAllocationForPeriod', {'periodId':jobAllocationPeriod.id}) }}" title="job allocations">
                                <span class="glyphicon glyphicon-user"></span>
                            </a>
                            <!-- </li> -->
                            <!-- </ul> -->
                        </td>
	            {% endif %}
                </tr>
            {% endfor %}

            {% if id < 0 %}
                <tr>
                    <td colspan="4">
                        New period for job allocations
                    </td>
                </tr>
                <tr>
        	    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                    <td>
	                {{ form_widget(form.startDate) }}
                    </td>
                    <td>
                        {{ form_widget(form.endDate) }}
                    </td>
                    <td>
                        {{ form_widget(form.groups) }}
                    </td>
                    <td>
                        {{ form_widget(form.save) }}
                        {{ form_widget(form.reset) }}
                    </td>
	            {{ form_end(form) }}
                </tr>
            {% endif %}
        </tbody>
    </table>

{% endblock core_content %}

src/Gesseh/CoreBundle/Resources/views/JobAllocationAdmin/manageJobAllocations.html.twig
{% extends "GessehCoreBundle::layout.html.twig" %}

{% block core_content %}

    <p>
        Job "{{ job.name }}"
    </p>

    <p>
        <a href='{{ path('GCore_AdminAllocateUserToJob', {'id': job.id}) }}'>add a user</a>
    </p>

    {% for jobAllocation in jobAllocations %}
        <p>
            {{ jobAllocation.startDate | date('d/m/Y') }} - {{ jobAllocation.endDate | date('d/m/Y') }} : {{ jobAllocation.user.name }}
            <a href='{{ path('GCore_AdminDeleteJobAllocation', {'id': jobAllocation.id}) }}'>delete</a>
        </p>
    {% endfor %}


{% endblock core_content %}

src/Gesseh/CoreBundle/Resources/views/JobAllocationAdmin/manageJobAllocationsForPeriod.html.twig
{% extends "GessehCoreBundle::layout.html.twig" %}

{% block core_content %}

    {% form_theme form 'GessehCoreBundle:Form:fields.html.twig' %}
    
    <h1>
        Period {{ jobAllocationPeriod.startDate|date("d/m/Y") }} - {{ jobAllocationPeriod.endDate|date("d/m/Y") }}
    </h1>
    {% if jobAllocationPeriod.completed == false %}
        {% if allUsersAllocated == true %}
            <p>
                <a href="{{ path('GCore_AdminJobAllocationPeriodCompletion', {'id':jobAllocationPeriod.id}) }}">
                    <span class="glyphicon glyphicon-lock"></span>
                    Set completed</a>
            </p>
        {% endif %}

        <form action="{{ path('GCore_AdminJobAllocationForPeriod', {'periodId': jobAllocationPeriod.id}) }}" method="post" class="form-horizontal">
            <div class="form-group">
                <label for="userId" class="col-sm-1 control-label">Next user</label>
                <div class="col-sm-5">
                    <select name="userId" id="userId" class="form-control">
                        {% for user in users %}
                            <option value="{{ user.id }}"  {% if nextUser is not null and user == nextUser %} selected{% endif %}>{{ user }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-1">
                    <input type="submit" name="save" value="Submit" class="btn btn-primary" />
                </div>
            </div>
        </form>
        
        <p>
            <a href="{{ path('GCore_AdminJobAllocationForPeriod', {'periodId':jobAllocationPeriod.id}) }}" class="btn btn-default">
                <span class="glyphicon glyphicon-refresh"></span>
                Reload job allocations</a>
        </p>
        
        {% for user in users %}
            {% if user == newJobAllocation.user %}
                <h2>
                    {{ user }}
                </h2>

                <ul>
                    {% for jobAllocation in jobAllocationPeriod.jobAllocations %}
                        {% if user == jobAllocation.user and newJobAllocation != jobAllocation %}
                            <li>
                                {{ jobAllocation.job }} : {{ jobAllocation.startDate|date("d/m/Y") }} - {{ jobAllocation.endDate|date("d/m/Y") }}
                                <a href='{{ path('GCore_AdminJobAllocationForPeriod', {'periodId':jobAllocationPeriod.id , 'userId':jobAllocation.user.id, 'jobAllocationId':jobAllocation.id}) }}'>modify</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <p>
                    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                </p>
            {% endif %}
        {% endfor %}
    {% endif %}

    <ul>
    {% for hospital in hospitals %}
        <li>
            {{ hospital }}
            <ul>
            {% for department in departments %}
                {% if hospital == department.hospital %}
                    <li>
                        {{ department }}
                        <ul>
                        {% for job in jobs %}
                            {% if department == job.department %}
                                <li>
                                    {#% set jobAllocationsNumber = 0 %#}
                                    {#% for jobAllocation in job.jobAllocations %#}
                                        {#% if jobAllocationPeriod ==  jobAllocation.jobAllocationPeriod %#}
                                            {#% set jobAllocationsNumber = jobAllocationsNumber + 1 %#}
                                        {#% endif %#}
                                    {#% endfor %#}
                                    {{ job }} ({{ job.maxAllocationsNumber }})
                                    <ul>
                                    {% for jobAllocation in jobAllocations %}
                                        {% if job == jobAllocation.job and jobAllocation != newJobAllocation %}
                                            <li {% if jobAllocation not in jobAllocationPeriod.jobAllocations %} class="inactive" title="belongs to another job allocation period"{% endif %}>
                                                {{ jobAllocation.user }}
                                                ({{ jobAllocation.startDate is empty ? "" : jobAllocation.startDate|date("d/m/Y") }} -
                                                {{ jobAllocation.endDate is empty ? "" : jobAllocation.endDate|date("d/m/Y") }})
                                                {% if jobAllocationPeriod.completed == false and jobAllocation in jobAllocationPeriod.jobAllocations %}
                                                    <a href="{{ path('GCore_AdminJobAllocationForPeriod', {'periodId':jobAllocationPeriod.id , 'userId':jobAllocation.user.id, 'jobAllocationId':jobAllocation.id}) }}" title="modify">
                                                        <span class="glyphicon glyphicon-edit"></span>
                                                    </a>
                                                {% endif %}
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    </ul>
                                </li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>

{% endblock core_content %}